name: test_bench
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7, <3.11
  - h5py
  - numpy=1.23.3
  - matplotlib
  - numba
  - scipy
  - pytest
  - pyaml
  - pip:
      - cython
      - pyfftw==0.13
      - pylians==0.3
