from bias_bench.io import BiasModelData

import numpy as np
import matplotlib.pyplot as plt
import Pk_library as PKL


def compute_bispectrum(field, Lbox, k1, k2, Ntheta):
    # FIXME: Enable use of double precision for the field
    field = field.astype(np.float32)
    theta = np.linspace(0, np.pi, Ntheta)

    # TODO: pipe out pylians parameters
    bbk = PKL.Bk(field, Lbox, k1=k1, k2=k2, theta=theta, MAS='CIC')

    # FIXME: combine this with power spectrum computation
    # Power spectrum for free
    # k = bbk.k  # k-bins for power spectrum
    # Pk = bbk.Pk # power spectrum

    return theta, {'bispectrum': bbk.B, 'reduced_bispectrum': bbk.Q}


def plot_bispectrum(bias_model_data: BiasModelData, k1=0.5, k2= 0.6, Ntheta=25, show_density=False):
    # TODO: Find out what k1, k2 values would be sensible so set as default
    l_box = bias_model_data.info['BoxSize']

    try:
        count_field = bias_model_data.count_field
        k_counts, bispec_counts = compute_bispectrum(count_field, l_box, k1, k2, Ntheta)
        plt.loglog(k_counts, bispec_counts['bispectrum'], label='predicted')
    except AttributeError:
        print("No predicted count field found in BiasModelData. Skipping plots")

    try:
        ground_truth = bias_model_data.count_field_truth
        k_truth, bispec_truth = compute_bispectrum(ground_truth, l_box, k1, k2, Ntheta)
        plt.loglog(k_truth, bispec_truth['bispectrum'], label='ground truth')
    except AttributeError:
        print("No ground truth count field found in BiasModelData. Skipping plots")

    if show_density:
        overdensity_field = bias_model_data.overdensity_field
        k_density, bispect_density = compute_bispectrum(overdensity_field, l_box, k1, k2, Ntheta)
        plt.loglog(k_density, bispect_density['bispectrum'], label="density")

    plt.xlabel(r"Angle $\theta$")
    plt.ylabel(r"$P(k)$ [$h^{-3}\mathrm{Mpc}^3$]")
    plt.suptitle("Bispectrum comparison of count fields")
    plt.title(f"Predicted count field generated by {bias_model_data.model_name}")
    plt.legend()
    plt.show()