num_bias_models: 1

bias_model_1:
  hdf5_file_path: bias_challenge/data/data.hdf5
  simulation_group_name: aquila_bias_challenge_training
  n_simulations: 1
  n_res: 1
  n_mass_bins: 1

  predict_counts_model: truncated_power_law
  predict_init_params: [100., 1., 0.01, 0.001]
  predict_counts_loss: poisson
  benchmark_optimizer: BFGS
  name: 'example'

plots:
  - ngal_vs_rho
  - power_bi_spectrum
#  - density_images

out_dir: ./examples

one_point:
  x_lim: [0, 1.5]
  y_lim: [-0.5, 3]

power_spectrum:
  show_density: false
  MAS:
  x_lim: [ 0, 1.5 ]
  y_lim: [ -0.5, 3 ]

bi_spectrum:
  show_density: false
  k1: 0.01
  k2: 0.02
  Ntheta: 25
  MAS:
